server:
  port: 50000
security:
  user:
    password: pass

spring:
  mvc:
    dispatch-options-request: true
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:file:~/h2/timesheeter
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
